# Generated by Django 5.2.3 on 2025-06-12 17:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0002_homecarousel_mission_publications_vision'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='pic',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='news_image'),
            preserve_default=False,
        ),
    ]
