# Generated by Django 5.2.3 on 2025-06-19 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0004_research_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homecarousel',
            name='image',
            field=models.ImageField(upload_to='carousel_images'),
        ),
        migrations.AlterField(
            model_name='news',
            name='pic',
            field=models.ImageField(upload_to='news_images'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='image',
            field=models.ImageField(upload_to='staff_images'),
        ),
    ]
