# Generated by Django 5.2.3 on 2025-06-19 12:18

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0005_alter_homecarousel_image_alter_news_pic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='image',
            field=models.ImageField(default=datetime.datetime(2025, 6, 19, 13, 18, 37, 882949), upload_to='news_images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='research',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
            preserve_default=False,
        ),
    ]
