# Generated by Django 5.2.3 on 2025-06-19 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0006_research_image_research_pub_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='pic',
            new_name='image',
        ),
    ]
